#pragma once

//Std includes
#include <vector>

//MakeLoader includes
#include "File.hpp"

/**
* This class represent the makefile generated by the application.
* The makefile is generated using the sources files in the "Sources" folder.
* @author Matrax
* @version 1.0
**/
class MakeFile : public File
{

    public:

        //Constructors and destructor
        MakeFile();
        ~MakeFile();

        //Overrided methods
        void generate() override;

        //Methods
        void createExecutable(std::vector<std::filesystem::path> sources);
        void createTarget(const std::string source, const std::string object);
        std::vector<std::filesystem::path> getSources(const std::string directory = "Sources") const;

};
