#pragma once

//Std includes
#include <vector>

//MakeLoader includes
#include "ApplicationFile.hpp"

//Json includes
#include "../../Includes/json.hpp"

/**
* This class represent the makefile generated by the application.
* The makefile is generated using the sources files in the "Sources" folder.
* @author Matrax
* @version 1.0
**/
class MakeFile : public ApplicationFile
{
    public:

        //Constructors and destructor
        MakeFile();
        MakeFile(const MakeFile &) = delete;
        virtual ~MakeFile();

        //Operators
        MakeFile & operator=(const MakeFile &) = delete;

        //Overrided methods
        void onCreate() override;

        //Methods
        void createBody();
        void createHeader(nlohmann::json configurations);
        void createStaticLibrary(std::vector<std::filesystem::path> sources);
        void createExecutable(std::vector<std::filesystem::path> sources);
        void createTarget(const std::string source, const std::string extension, const std::string object);
        void createVariable(const std::string name, const std::string value = "");
        void createCommand(const std::string name, const std::string requirement = "", const std::string command = "");
        std::vector<std::filesystem::path> getSources(const std::string directory = "Sources") const;

};
