#pragma once

#include <filesystem>
#include <iostream>
#include <string>
#include <vector>
#include <fstream>

/**
* This class represent the makefile generated by the application.
* The makefile is generated using the sources files in the "Sources" folder.
* @author Matrax
* @version 1.0
**/
class Makefile 
{

    private:

        //Attributes
        std::ofstream m_file;
        std::string m_content;

    public:

        //Constructors and destructor
        Makefile();
        Makefile(const Makefile &) = delete;
        virtual ~Makefile();

        //Operators
        Makefile & operator=(const Makefile &) = delete;

        //Methods
        void build();
        void open();
        void save();
        void createCommand(const std::string name, const std::string value);
        void createVariable(const std::string name, const std::string value);
        void createExecutable(const std::vector<std::string> & sources);
        void createTarget(const std::string name);
        std::vector<std::string> getSources() const;

};
